apiVersion: v1
kind: Namespace
metadata:
  labels:
    env: dev
    team: jx
    certmanager.k8s.io/disable-validation: "true"
    gitops.jenkins-x.io/pipeline: 'cluster'
    gitops.jenkins-x.io/boot-namespace: 'jx'
  name: jx
