apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  labels:
    name: nginx
    gitops.jenkins-x.io/pipeline: 'cluster'
    gitops.jenkins-x.io/boot-namespace: 'jx'
  name: nginx
spec: {}
status: {}
